version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: rsvp-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  app:
    image: jaybarb1990/rsvp-app
    ports:
      - "3000:3000"
