@host = http://localhost:3000

### Create table
GET {{host}}/createTable

### Get all rows from rsvps table
GET {{host}}/get_all_rsvps

### create a rsvp
POST {{host}}/rsvps
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "rsvp_response": true,
    "number_of_guests": 2
}